for n in range(3):
    for ma in mali:
        main(numUAV[n],ma,TruePositiveArray,FPArray,FNArray,Accuracy,Precision)
        #basicScheme(numUAV[n],ma,B_TruePositiveArray,B_FPArray,B_FNArray,B_Accuracy,B_Precision)
    lab = "numUAV= " + str(numUAV[n])
    #f1 = plt.figure(1)
    #plt.plot(mali,detectedArray,label=lab,marker="o")
    #plt.xlabel("Num of Malicious UAVs %")
    #plt.ylabel("Detection Rate")
    #plt.legend()
    figure, axis = plt.subplots(2, 3)
    axis[0, 0].plot(mali,TruePositiveArray,label=lab,marker="o")
    axis[0, 0].set_title("Detection Rate")
    axis[0, 0].legend()
    #f1 = plt.figure(1)
    #plt.plot(mali,TruePositiveArray,label=lab,marker="o")
    #plt.xlabel("Num of Malicious UAVs %")
    #plt.ylabel("True Positive Rate Main")
    #plt.legend()
    
    #f2 = plt.figure(2)
    #plt.plot(mali,FPArray,label=lab,marker="o")
    #plt.xlabel("Num of Malicious UAVs %")
    #plt.ylabel("False Positive Rate")
    #plt.legend()
    axis[0, 1].plot(mali,FPArray,label=lab,marker="o")
    axis[0, 1].set_title("False Positive Rate")
    axis[0, 1].legend()
    #f3 = plt.figure(3)
    #plt.plot(mali,FNArray,label=lab,marker="o")
    #plt.xlabel("Num of Malicious UAVs %")
    #plt.ylabel("False Negative Rate")
    #plt.legend()
    axis[1, 0].plot(mali,FNArray,label=lab,marker="o")
    axis[1, 0].set_title("False Negative Rate")
    axis[1, 0].legend()
    #f4 = plt.figure(4)
    #plt.plot(mali,Accuracy,label=lab,marker="o")
    #plt.xlabel("Num of Malicious UAVs %")
    #plt.ylabel("Accuracy Rate")
    #plt.legend()
    axis[1, 1].plot(mali,Accuracy,label=lab,marker="o")
    axis[1, 1].set_title("Accuracy Rate")
    axis[1, 1].legend()
    #f5 = plt.figure(5)
    #plt.plot(mali,Precision,label=lab,marker="o")
    #plt.xlabel("Num of Malicious UAVs %")
    #plt.ylabel("Precision Rate")
    #plt.legend()
    axis[1, 2].plot(mali,Precision,label=lab,marker="o")
    axis[1, 2].set_title("Precision Rate")
    axis[1, 2].legend()
    #detectedArray.clear()
    FPArray.clear()
    FNArray.clear()
    Accuracy.clear()
    Precision.clear()
    TruePositiveArray.clear()